CREATE TABLE AUTHOR (
    id INTEGER NOT NULL AUTO_INCREMENT,
    firstname VARCHAR(128) NOT NULL,
    lastname VARCHAR(128) NOT NULL
);

CREATE TABLE GENRE (
    id INTEGER NOT NULL AUTO_INCREMENT,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE BOOKS (
    id INTEGER NOT NULL AUTO_INCREMENT,
    title VARCHAR(128) NOT NULL,
    AUTHOR_lastname VARCHAR(128) NOT NULL,
    GENRE_name VARCHAR(128) NOT NULL,
    PRIMARY KEY (id)
);