CREATE TABLE AUTHOR (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE GENRE (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE BOOKS (
    id IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    GENRE_id BIGINT NOT NULL,
    AUTHOR_id BIGINT NOT NULL,
    FOREIGN KEY (GENRE_id) REFERENCES GENRE (id),
    FOREIGN KEY (AUTHOR_id) REFERENCES AUTHOR (id)
);
