CREATE TABLE AUTHOR (
    id IDENTITY NOT NULL PRIMARY KEY,
    firstname VARCHAR(128) NOT NULL,
    lastname VARCHAR(128) NOT NULL
);

CREATE TABLE GENRE (
    id IDENTITY NOT NULL PRIMARY KEY,
    name VARCHAR(128) NOT NULL
);

CREATE TABLE BOOKS (
    id IDENTITY NOT NULL PRIMARY KEY,
    title VARCHAR(128) NOT NULL,
    GENRE_name VARCHAR(128),
    FOREIGN KEY (GENRE_name) REFERENCES GENRE (name)
);

CREATE TABLE LIBRARY (
    id IDENTITY NOT NULL PRIMARY KEY,
    BOOK_title VARCHAR(128) NOT NULL,
    AUTHOR_lastname VARCHAR(128) NOT NULL,
    FOREIGN KEY (BOOK_title) REFERENCES BOOKS (title),
    FOREIGN KEY (AUTHOR_lastname) REFERENCES AUTHOR (lastname)
);

